version: '3'
services:
 airflow_webserver:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"  # Expose the Airflow webserver port
   # volumes:
   # DAGs copied directly in Dockerfile, preference would be to use volumes section
   #  - ./stocks_ETL_project/airflow/dags:/usr/local/airflow/dags  # Update the path to your local DAGs directory
  # Space for other volumes or configurations
   command: ["airflow", "webserver", "--port", "8080"]