version: '3'
services:
  airflow_webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"   # Expose the Airflow webserver port
    volumes:
      - /path/to/airflow/dags:/usr/local/airflow/dags   # Mount DAGs directory to the container
      # Space for other volumes or configurations
    command: ["airflow", "webserver", "--port", "8080"]

    # remember to run airflow db init --version 2.6.3 to initialise meta db